name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: [20]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Manuscript validate
        if: ${{ hashFiles('data/manuscript.txt') != '' }}
        run: npm run manuscript:validate -- data/manuscript.txt

      - name: Deterministic CLI smoke (if script & manuscript present)
        if: ${{ hashFiles('data/manuscript.txt') != '' }}
        run: |
          if npm run | grep -q cli:test:nix; then
            npm run cli:test:nix
          else
            echo "cli:test:nix script not found, skipping"
          fi

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test -- --run

      - name: Performance (5MB synthetic) timing
        run: |
          echo "Running performance.large.spec.ts"
          start=$(node -p "performance.now()") || true
          npm test -- --run --filter=performance.large.spec.ts || true
          # Extract timing from console warn if present
          echo "Completed performance test"

      - name: Summary
        if: ${{ always() }}
        run: |
          echo "OS: ${{ matrix.os }}" >> $GITHUB_STEP_SUMMARY
          echo "Node: ${{ matrix.node }}" >> $GITHUB_STEP_SUMMARY
          echo "Tests executed on matrix combination." >> $GITHUB_STEP_SUMMARY

      - name: Upload test report artifact (if present)
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-report-${{ matrix.os }}
          path: out/test-report.md
          if-no-files-found: ignore
