name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Manuscript validate
        if: ${{ hashFiles('data/manuscript.txt') != '' }}
        run: npm run manuscript:validate -- data/manuscript.txt
        continue-on-error: true

      - name: Deterministic CLI smoke (if script & manuscript present)
        if: ${{ hashFiles('data/manuscript.txt') != '' }}
        run: |
          if npm run | grep -q cli:test:nix; then
            npm run cli:test:nix || true
          else
            echo "cli:test:nix script not found, skipping"
          fi
        continue-on-error: true

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test -- --run

      - name: Upload test report artifact (if present)
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-report
          path: out/test-report.md
          if-no-files-found: ignore
